trigger:
- main

pool:
  name: Jatto

steps:
- 
- task: SonarQubePrepare@6
  inputs:
    SonarQube: 'sonar'
    scannerMode: 'CLI'
    cliVersion: '4.8'
    configMode: 'manual'
    cliProjectKey: 'p1'
    cliProjectName: 'p1'
    cliSources: '.'

- task: SonarQubePublish@6
  inputs:
    pollingTimeoutSec: '300'

- task: SonarQubeAnalyze@6
  inputs:
    jdkversion: 'JAVA_HOME'