trigger:
  branches:
    include:
      - main  # or master, or whatever branch you want to trigger the pipeline

pool:
  vmImage: 'task-master'  # Use an Ubuntu-based agent. You can change this based on your needs.

steps:
- task: UseGitVersion@5  # Optional: Ensures git is used at a specific version
  inputs:
    versionSpec: '>=2.37.0'
  displayName: 'Ensure Git Version'

- task: Checkout@1
  inputs:
    fetchDepth: 0  # Clone the full history for the repo
  displayName: 'Clone Repository'

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'  # Path to the pom.xml file in the repo
    goals: 'test'
  displayName: 'Run Maven Tests'

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'  # Path to the pom.xml file in the repo
    goals: 'package'         # You can also use 'clean install' depending on your build strategy
  displayName: 'Build with Maven'