name: CICD

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn package --file pom.xml

    - name: Post job cleanup
      run: |
        export ACTIONS_RUNNER_DEBUG=true
        /usr/bin/tar --posix -cf cache.tzst --exclude cache.tzst -P -C /home/charles/project-folder/Task-Master-Pro/actions-runner/_work/Task-Master-Pro/Task-Master-Pro --files-from manifest.txt --use-compress-program zstdmt || echo "Cache save failed"
